### PR TITLE
Zero to snowflake

### PR DESCRIPTION
**Pull request by msteadly**

### CODE REVIEW

**Comment by msteadly** [comment]
Approved

**Comment by msteadly** [comment]
Good to go

**Comment by drewbanin** [comment]
@msteadly hey there - this is a PR to the `fishtown-analytics/dbt-starter-project` repo. This repo is the Fishtown Analytics version of the repo, and it represents the code that gets cloned when a user runs `dbt init`! Just wanted to give you a heads up that you probably wanted to open this PR against your fork of the repo instead of this repo itself :) 

Glad you're kickin dbt around - join us in [Slack](https://community.getdbt.com) if there's anything we can help out with 😄

**Comment by msteadly** [comment]
Hey Drew,

Sorry about that. Accidentally PRed to your repo rather mine.

Also - For CI integration, how do you initiate a run something upon a PR?

-Michael Stead

**Comment by drewbanin** [comment]
not a problem :).

If you're using dbt Cloud, you can turn this on by enabling builds on PRs. Check out [the docs on enabling continuous integration with GitHub](https://docs.getdbt.com/docs/dbt-cloud/using-dbt-cloud/cloud-enabling-continuous-integration-with-github) for more info.

**Pull request closed without merging**
