### PR TITLE
Update dbt_project.yml

### PR DESCRIPTION
**Pull request by clrcrl**
I'm not sure whether we need to re-create the [tag](https://github.com/fishtown-analytics/dbt-starter-project/releases).

### CODE REVIEW

**Comment by drewbanin** [comment]
This is a little bit tricky -- we don't want to merge directly into `master` as any `dbt init` invocations that happen on dbt <0.17.0 will get an invalid `dbt_project.yml` file. I think we could replace the existing tag, but that's a little bit gross too.

@beckjake what's the right way to make a change like this?

**Comment by beckjake** [comment]
I think the answer here is always going to be a little gross! We want to just update the tag and merge this into something that _isn't_ `master`.

The ideal answer is probably to go back in time and clone from a tag (or version-specific branch) for `dbt init` from the outset, and then you can merge to master as much as you like. As it is you can't merge to master without breaking every previous dbt version's `dbt init`.

The options as I see them are:
 - break everyone with older dbt versions (not really an option!)
 - make a new git repo named `dbt-starter-project-v2` or whatever
 - make a branch for config version 2 and update it in never-backwards-incompatible ways
 - make a tag for config version 2 and update it in never-backwards-incompatible ways

I did a tag because it seemed easier than a branch, but it would be fine to delete the tag and recreate it as a branch, or just re-point the tag to 3521fab. They're kind of equivalent.

**Comment by drewbanin** [comment]
@clrcrl based on our conversation this morning, do we even want to make this change? The `+` is optional here!

**Comment by clrcrl** [comment]
Sigh, I don't know.
TBH I don't love that it's optional — it's just an extra thing that needs explaining. I don't think we've written it in the docs anywhere that it's optional (have we?), I'd prefer to almost pretend that it's required, and as a result have consistent `+`s everywhere.

**Comment by heisencoder** [comment]
It looks like this issue will need to be resolved somehow before 0.19 launches, since it appears that 0.19 requires `config-version: 2` now.  When I use dbt Cloud with 0.19 beta and the dbt-starter-project, it's immediately broken.

**Comment by drewbanin** [comment]
hey @heisencoder - we have a tag in this repo, [dbt-yml-config-version-2](https://github.com/fishtown-analytics/dbt-starter-project/tree/dbt-yml-config-version-2) which uses a dbt v0.19.0 compatible `dbt_project.yml` file. We definitely do intend to make dbt Cloud clone this new tag, but haven't quite gotten there yet as 0.19.0 is still in pre-release mode!

FWIW, I feel that this starter project could probably use a bit of a refresh and could benefit from demo'ing some of the newer functionality in dbt that's rolled out over the past year or so. I think that would make for a much nicer first-time dbt experience for both open source and dbt Cloud users!

**Comment by heisencoder** [comment]
Hi Drew!

Thanks for pointing out the `dbt-yml-config-version-2` tag!  I went ahead and opened up issue #10 (before seeing your reply), so will move the conversation over there.

**Pull request closed without merging**
